[env:adafruit_feather_esp32_v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = bblanchon/ArduinoJson@^7.4.3
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L