#ifndef OTA_PUBLIC_KEY_H
#define OTA_PUBLIC_KEY_H

// Generated by scripts/ota-tool.py generate
// Do not commit ota_private.pem.

const char OTA_PUBLIC_KEY_PEM[] =
  "-----BEGIN PUBLIC KEY-----\n"
  "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwEhEjPJRaw5JRESgg7ZjN7v2uukB\n"
  "rug1lR4OH7PEp9CDqlD7ZimzI5M+kjqPBME01zPEI0rmsJtdNZQA8ZIeVg==\n"
  "-----END PUBLIC KEY-----\n"
;

#endif // OTA_PUBLIC_KEY_H
